language: node_js
node_js:
- v12.18.3
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_2fc69c4133c3_key -iv $encrypted_2fc69c4133c3_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
install: npm install
script:
- npm run build
after_success:
- chmod 600 ~/.ssh/id_rsa
- rsync -e 'ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no' -r ./build/* travis@120.27.247.30:~/scoyzhao-admin
